name: Scrape

# Controls when the workflow will run
on:
  
  schedule:
    - cron:  '15 4 * * *'   
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: chicago-scraper

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt          
      - name: run scraper
        run: make
      - name: keepalive
        uses: gautamkrishnar/keepalive-workflow@v1
      - name: export
        run: |
          zip cmap.db.zip cmap.db
      - name: Push data
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
        with:
          upload_url: https://uploads.github.com/repos/datamade/chicago-council-scrapers/releases/80533645/assets{?name,label}
          release_id: 80533645 # same as above (id can just be taken out the upload_url, it's used to find old releases)
          asset_path: ./cmap.db.zip # path to archive to upload
          asset_name: cmap.db.zip # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
          asset_content_type: application/zip # required by GitHub API
